'use client';
import { useEffect, useState } from 'react';
import { CalendarDays, CloudSun, Settings, Sun, Cloud, CloudRain, Snowflake, CloudLightning, Image as ImageIcon } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { photoOrder } from '@/lib/photo-order';
import { eventTimeRange } from '@/lib/event-time';
import { DailyHighlights, HighlightsData } from '@/components/daily-highlights';

type Event = {id:string; title:string; start:string; end:string; allDay:boolean; location:string};
type SettingsData = {windows:string[][]; photo_seconds:number};
type Data = {today:string; week:string[]; events:Event[]; photos:string[]; weather:any; status:Record<string,{updated:number; error:string|null}>; settings:SettingsData; display:{on:boolean; override_until:number; error:string|null}; demo?:boolean; highlights?:HighlightsData; display_title?:string};
const tz='America/Denver';
const dayDate=(s:string)=>new Date(s+'T12:00:00');
const localDay=(d:Date)=>new Intl.DateTimeFormat('en-CA',{timeZone:tz,year:'numeric',month:'2-digit',day:'2-digit'}).format(d);
function condition(code:number){if(code===0)return 'Clear';if(code<=3)return 'Partly cloudy';if(code<=48)return 'Fog';if(code<=67)return 'Rain';if(code<=77)return 'Snow';if(code<=82)return 'Showers';if(code<=86)return 'Snow showers';return 'Thunderstorms'}
function WeatherIcon({code=0}:{code?:number}){const Icon=code===0?Sun:code<=2?CloudSun:code<=48?Cloud:code<=67?CloudRain:code<=77?Snowflake:code<=82?CloudRain:code<=86?Snowflake:CloudLightning;return <Icon aria-hidden="true"/>}
function includesDay(e:Event,day:string){if(e.allDay)return day>=e.start && day<e.end;const start=localDay(new Date(e.start));const end=localDay(new Date(Math.max(Date.parse(e.start),Date.parse(e.end)-1)));return day>=start&&day<=end}
export default function Home(){
 const [data,setData]=useState<Data|null>(null),[now,setNow]=useState<Date|null>(null),[offline,setOffline]=useState(false),[photo,setPhoto]=useState(0),[settingsOpen,setSettingsOpen]=useState(false),[form,setForm]=useState<SettingsData>({windows:[['06:00','08:30'],['16:30','19:00']],photo_seconds:60}),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false);
 async function refresh(){try{const r=await fetch('/api/state',{cache:'no-store'});if(!r.ok)throw Error();const value=await r.json() as Data;setData(previous=>({...value,photos:photoOrder(value.photos,previous?.photos)}));setOffline(false)}catch{setOffline(true)}}
 useEffect(()=>{setNow(new Date());refresh();const a=setInterval(()=>setNow(new Date()),1000),b=setInterval(refresh,15000);return()=>{clearInterval(a);clearInterval(b)}},[]);
 useEffect(()=>{const id=setInterval(()=>setPhoto(p=>p+1),1000*(data?.settings.photo_seconds||60));return()=>clearInterval(id)},[data?.settings.photo_seconds]);
 useEffect(()=>{const id=setInterval(()=>{document.querySelectorAll('.events').forEach(el=>{if(el.scrollHeight>el.clientHeight){el.scrollTop=el.scrollTop+el.clientHeight>=el.scrollHeight-4?0:el.scrollTop+Math.floor(el.clientHeight*.7)}})},20000);return()=>clearInterval(id)},[]);
 async function change(path:string,body:unknown){setBusy(true);setNotice('');try{const r=await fetch(path,{method:'POST',headers:{'Content-Type':'application/json','X-Family-Wall':'1'},body:JSON.stringify(body)});const res=await r.json() as {error?:string};if(!r.ok)throw Error(res.error||'Could not save');setNotice('Saved');await refresh()}catch(e){setNotice(e instanceof Error?e.message:'Could not save')}finally{setBusy(false)}}
 const weather=data?.weather, current=weather?.current, daily=weather?.daily;
 const today=data?.today||(now?localDay(now):'');
 const activePhoto=data?.photos.length?data.photos[photo%data.photos.length]:null;
 const statuses=data?Object.entries(data.status).filter(([name,s])=>s.error||!s.updated||Date.now()/1000-s.updated>({calendar:900,weather:3600,photos:3600} as Record<string,number>)[name]):[];
 return <main className="wall">
  <header className="top"><div className="brand"><div className="eyebrow">{data?.display_title || 'FAMILY WALL'}</div><h1>{now?now.toLocaleDateString('en-US',{timeZone:tz,weekday:'long',month:'long',day:'numeric'}):'Welcome home'}</h1></div><DailyHighlights data={data?.highlights} today={today}/><div className="current-weather"><WeatherIcon code={current?.weather_code}/><div><strong>{current?Math.round(current.temperature_2m)+'°':'—'}</strong><span>Local · °F</span></div><p>{current?condition(current.weather_code):'Weather connecting'}</p></div><div className="clock">{now?now.toLocaleTimeString('en-US',{timeZone:tz,hour:'numeric',minute:'2-digit'}):'—'}<small>Mountain time</small></div></header>
  {data?.demo&&<div className="demo-banner">LAYOUT PREVIEW · Sample calendar events. Connect your Pi to show your Family calendar.</div>}
  <div className="main-grid"><section className="calendar"><div className="section-heading"><h2><CalendarDays/> Our week</h2><span>{data?.week.length?dayDate(data.week[0]).toLocaleDateString('en-US',{month:'short',day:'numeric'})+' – '+dayDate(data.week[6]).toLocaleDateString('en-US',{month:'short',day:'numeric'}):'Family calendar'}</span></div>
  <div className="week">{data?.week.map(day=>{const events=data.events.filter(e=>includesDay(e,day));return <article className={'day '+(day===today?'today':'')} key={day}><div className="day-heading"><span>{dayDate(day).toLocaleDateString('en-US',{weekday:'short'})}</span><strong>{dayDate(day).getDate()}</strong>{day===today&&<em>TODAY</em>}</div><div className="events">{events.length?events.map(e=><div className={'event '+(e.allDay?'all-day':'')} key={e.id}><span>{e.allDay?'ALL DAY':eventTimeRange(e.start,e.end,tz)}</span><h3>{e.title}</h3></div>):<p className="empty-day">{data.status.calendar.updated?'Nothing planned': 'Waiting for calendar'}</p>}</div></article>})}{!data&&<div className="connecting"><CalendarDays/><h2>Connecting to Family</h2><p>{offline?'The dashboard service is unavailable. Retrying automatically.':'Getting your week ready…'}</p></div>}</div></section>
  <aside className="photo-panel"><div className="photo-frame">{activePhoto?<img key={activePhoto} src={activePhoto} alt="From the Family Wall photo album" onError={()=>setPhoto(p=>p+1)}/>:<div className="photo-empty"><ImageIcon/><h2>Family moments</h2><p>{data?.status.photos.error||'Your album photos will appear here.'}</p></div>}</div><div className="photo-caption"><span>FAMILY MOMENTS</span><span>{data?.photos.length?`${photo%data.photos.length+1} / ${data.photos.length}`:'Shared album'}</span></div></aside></div>
  <section className="forecast"><div className="forecast-label"><CloudSun/><h2>The days ahead</h2><span>Your location</span></div>{daily?.time.slice(0,5).map((date:string,i:number)=><div className="forecast-day" key={date}><span>{i===0?'Today':dayDate(date).toLocaleDateString('en-US',{weekday:'short'})}</span><WeatherIcon code={daily.weather_code[i]}/><strong>{Math.round(daily.temperature_2m_max[i])}° <small>{Math.round(daily.temperature_2m_min[i])}°</small></strong><p>{daily.precipitation_probability_max[i]??0}% rain / snow</p></div>)}{!daily&&<p>Forecast will appear after the first weather update.</p>}</section>
  <footer><div className="status" role="status">{offline?'Connection interrupted · Showing last received information':statuses.length?statuses.map(([name,s])=>`${name}: ${s.error||'waiting for update'}${s.updated?' · last updated '+new Date(s.updated*1000).toLocaleTimeString('en-US',{timeZone:tz,hour:'numeric',minute:'2-digit'}):''}`).join(' · '):'Family calendar · Updated automatically'}{data?.display.error&&' · '+data.display.error}</div><a href="https://open-meteo.com/" target="_blank" rel="noreferrer">Weather: Open-Meteo · CC BY 4.0</a><Button variant="ghost" onClick={()=>{setForm(data?.settings||form);setNotice('');setSettingsOpen(!settingsOpen)}}><Settings/> Display settings</Button></footer>
  {settingsOpen&&<section className="settings-panel" aria-label="Display settings"><div className="section-heading"><h2>Display settings</h2><Button variant="outline" onClick={()=>setSettingsOpen(false)}>Close</Button></div><p>Every day · Mountain time</p><form onSubmit={e=>{e.preventDefault();change('/api/settings',form)}}>{form.windows.map((w,i)=><div className="window-row" key={i}><strong>{i===0?'Morning':'Afternoon'}</strong>{w.map((v,j)=><label key={j}>{j===0?'On':'Off'}<Input type="time" required value={v} onChange={e=>setForm({...form,windows:form.windows.map((row,r)=>r===i?row.map((x,c)=>c===j?e.target.value:x):row)})}/></label>)}</div>)}<label>Seconds per photo<Input type="number" min="15" max="3600" value={form.photo_seconds} onChange={e=>setForm({...form,photo_seconds:Number(e.target.value)})}/></label><Button disabled={busy} type="submit">Save schedule</Button></form><div className="override"><Button disabled={busy} variant="outline" onClick={()=>change('/api/override',{minutes:60})}>Turn on for 1 hour</Button><Button disabled={busy} variant="outline" onClick={()=>change('/api/override',{minutes:0})}>Resume schedule</Button></div><p role="status">{notice}</p></section>}
 </main>
}
